### ISSUE TITLE
Access to TARGET variable in tests

### ISSUE THREAD

**Issue by casey** [japaric/cross#100]
I have integration tests which run a binary. Normally, they invoke "target/debug/foo". However, when testing under cross, the binaries are in "target/TARGET/debug/foo".

Would it be possible to export the TARGET variable so that they can be accessed in tests and used to locate built binaries?

I would use "cargo run" but I need to change the cwd of the process to one not under the crate root, so that won't work.

**Comment by casey** [comment]
Apologies, this might be a duplicate of #76.

**Comment by japaric** [comment]
> I have integration tests which run a binary. 

Are these run using `cross test`? If so, I think you can use `env::current_exe` to get the path to the test executable, which is in the `target/$TARGET/debug` directory. From there you can work your way to `target/$TARGET/debug/foo`. I suggest using [this snippet](https://github.com/japaric/itm/pull/9/files#diff-419204883b494bec04ba78c2e882a6ddR23) to find `foo`.

**Comment by casey** [comment]
Ah, okay, that definitely works.

**Comment by casey** [comment]
And thanks for cross! It used it + trust to get builds and binaries [for this command runner thingy](https://github.com/casey/just) on a bunch of platforms. It definitely saved me a ton of work.
