### ISSUE TITLE
Missing v0.1.11 tags for x86_64-unknown-linux-gnu has broken cross

### ISSUE THREAD

**Issue by Susurrus** [japaric/cross#108]
It looks like the v0.1.11 tag wasn't deployed for the `x86_64-unknown-linux-gnu` target. This has broken testing for us.

**Comment by japaric** [comment]
Err, it seems our x86_64-linux build got removed from the .travis.yml file and that's why there's no Cross release fo that target. I'll make a manual release.

**Comment by CryZe** [comment]
Nice, at least my code seems to build again with the v0.1.11 image pushed now :)

**Comment by japaric** [comment]
This has now been fixed.

**Comment by japaric** [comment]
Thanks for reporting @Susurrus! And thanks @CryZe for checking.
