### ISSUE TITLE
Cross fails with error: `"rustup" "target" "list"` failed with exit code: Some(1) 

### ISSUE THREAD

**Issue by asomers** [japaric/cross#111]
https://github.com/nix-rust/nix has been using cross for its CI tests for a few months now.  But on about 25-June, all of our Travis builds started to fail with the error message:

    error: "rustup" "target" "list" failed with exit code: Some(1)

I don't know why it started on 25-June. It's probably either a change to Travis (they updated their builders, but they claim it was done by 21-June), or Rustup, or Cross.  It looks like cross is refusing to run without a default target, even though cross itself should be installing the toolchain.  Do you have any idea why?  At the very least, it should print rustup's full error message.

https://travis-ci.org/nix-rust/nix/builds/246718360

Downstream bug: https://github.com/nix-rust/nix/issues/634

**Comment by asomers** [comment]
I notice that rustup 1.5.0 was release at about the same time as our builds began to fail.  Perhaps that's the cause.  I'll try to setup a VM to use rustup 1.4.0.

**Comment by Susurrus** [comment]
I'm running this locally and I have rustup 1.5 and I can't reproduce the issue.

**Comment by asomers** [comment]
Turned out to be a conflict between the rustup 1.5.0 release and Travis's cache feature.  Clearing caches fixed the problem.  It had nothing to do with cross after all.  Sorry for the false alarm.
