### ISSUE TITLE
Cross errors on libudev, not downloading image on mac

### ISSUE THREAD

**Issue by syncharny** [japaric/cross#115]
Seems like the docker images are not being used on mac, or something else. Any idea why this fails?

> cross build --target armv7-unknown-linux-gnueabihf
>    Compiling pkg-config v0.3.9
>    Compiling libc v0.2.26
>    Compiling ioctl-rs v0.1.5
>    Compiling termios v0.2.2
>    Compiling libudev-sys v0.1.3
> error: failed to run custom build command for `libudev-sys v0.1.3`
> process didn't exit successfully: `/Users/davidsacharny/src/rpi-radar/target/debug/build/libudev-sys-2a5dbb0d37b2dc2b/build-script-build` (exit code: 101)
> --- stderr
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"', src/libcore/result.rs:859
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by japaric** [comment]
> Seems like the docker images are not being used on mac

macOS is not supported as a host; this is written in README:

> Disclaimer: Only works on a x86_64 Linux host (e.g. Travis CI is supported)

In that case `cross` behaves as an alias for Cargo so you are seeing the same output as running `cargo build --target ..`.

Closing as this is expected behavior.

**Comment by Progdrasil** [comment]
I'm Having this same issue running on manjaro
