### ISSUE TITLE
japaric/x86_64-unknown-linux-gnu:v0.1.12 is missing

### ISSUE THREAD

**Issue by CryZe** [japaric/cross#126]
Looks like all docker images but japaric/x86_64-unknown-linux-gnu got updated.

**Comment by CryZe** [comment]
Interestingly, this happened in the last release too: https://github.com/japaric/cross/issues/108

So it seems like whatever happened back then, didn't get fixed properly.

**Comment by bwasty** [comment]
I've got the same problem.

**Comment by japaric** [comment]
I've pushed the image manually. I'll send a PR to fix the automatic release problem later on.
