### ISSUE TITLE
sparc64 builds don't work with v0.1.12 anymore

### ISSUE THREAD

**Issue by CryZe** [japaric/cross#127]
With 0.1.11:
https://travis-ci.org/CryZe/livesplit-core/jobs/278234679

With 0.1.12:
https://travis-ci.org/CryZe/livesplit-core/jobs/278851207

```
error: linking with `qemu-sparc64` failed: exit code: 1
...
  = note: qemu: unknown option 'Wl,--as-needed'
```

**Comment by japaric** [comment]
That's a fun error Cross is using QEMU to link binaries ... *sigh* why the test suite didn't catch this?

I think I can fix this manually without a new release.

**Comment by japaric** [comment]
This should be fixed now.

**Comment by CryZe** [comment]
Thank you :)
