### ISSUE TITLE
Solaris target

### ISSUE THREAD

**Issue by bgermann** [japaric/cross#134]
In rust-lang/rust#45001 I was pointed here. I am thinking of adding support for Solaris. @malbarbo asked for SPARC support, but at least a sparc64-unknown-linux-gnu already exists. I would build sparcv9-sun-solaris and x86_64-sun-solaris.

As I read through the sources, they seem to be similar to the Docker CI stuff in rust-lang/rust. Also there is alexcrichton/port-of-rust, which also seems to have the same roots. Would it be preferable to have a [prebuilt](https://github.com/alexcrichton/port-of-rust/tree/master/prebuilt) Solaris Docker image to reuse here?

**Comment by malbarbo** [comment]
Thanks @bgermann for taking a look at cross. I mean to ask for Solaris support, I was kind of :sleeping:, sorry.

The Docker stuff is similar to that of rust-lang/rust, so you are in a good position for adding cross support for Solaris :grin:.

> Would it be preferable to have a prebuilt Solaris Docker image to reuse here?

The prebuilt images are not being used anymore (the only exceptions, I think, are [freebsd](https://github.com/rust-lang/libc/blob/master/ci/docker/x86_64-unknown-freebsd/Dockerfile) and [netbsd](https://github.com/rust-lang/libc/blob/master/ci/docker/x86_64-rumprun-netbsd/Dockerfile) on https://github.com/rust-lang/libc). Sadly there are a lot of repetitions... I had to add support for android and emscripten in three repositories: https://github.com/rust-lang/rust, https://github.com/rust-lang/libc and https://github.com/japaric/cross. I think that in the future libc could use cross, but https://github.com/rust-lang/rust have different needs. So for now, adding Docker files in cross should be enough. What do you think @japaric?

**Comment by bgermann** [comment]
I have seen the use in libc and want to create Solaris CI support there as well. As there is no cross compiler for it in Ubuntu, binutils/gcc have to be built, which takes a long time. It is the same for *BSD, so I guess this is the reason for them relying on a prebuilt image with cross-gcc installed.

But if there are concrete plans that libc will use cross for their testing, I will only add support here without a prebuilt image.
