### ISSUE TITLE
cannot run binary built for Solaris

### ISSUE THREAD

**Issue by apopiak** [japaric/cross#150]
I'm trying to cross-compile a super small test project for Solaris, but `cross` fails with `could not execute process '/target/x86_64-sun-solaris/release/crosstest' (never executed)`.
My command: `cross run --release --target=x86_64-sun-solaris -v` on a Ubuntu 17.04 system.
I went into the docker container and it's a Ubuntu container so I'm not surprised that the Solaris binary cannot execute.
I'm confused where I went wrong because I saw the PR that added Solaris support.

**Comment by japaric** [comment]
As the README [states](https://github.com/japaric/cross#supported-targets) there's cross *compilation* support for Solaris targets but *not* run / test support.

> I went into the docker container and it's a Ubuntu container so I'm not surprised that the Solaris binary cannot execute.

Other targets have run / test support via QEMU / Wine. Nobody has suggested a way to do the same for Solaris -- QEMU user emulation may not work but QEMU system emulation would probably work.

**Comment by apopiak** [comment]
Thanks, for clarifying. Got tripped up by that detail I guess. Is it possible to cross-compile rustc and or cargo for Solaris?

**Comment by japaric** [comment]
> Is it possible to cross-compile rustc and or cargo for Solaris?

Cross compiling Cargo works for me:

``` console
$ cross build --target sparcv9-sun-solaris
$ file target/sparcv9-sun-solaris/debug/cargo
target/sparcv9-sun-solaris/debug/cargo: ELF 64-bit MSB executable, SPARC V9, total store ordering, version 1 (SYSV), dynamically linked, interpreter /usr/lib/sparcv9/ld.so.1, with debug_info, not stripped
```

I don't know if you can use Cross to cross compile rustc. rust-lang/rust has its own build system called `bootstrap` that calls *Cargo* to build std, rustc, etc. Perhaps you could hack it to make it call Cross instead of Cargo? I haven't tried.

**Comment by apopiak** [comment]
Just FYI, I'm trying to build for `x86_64-sun-solaris`. I've tried to follow your [reddit post](https://www.reddit.com/r/rust/comments/5ag60z/how_do_i_bootstrap_rust_to_crosscompile_for_a_new/) on cross-compiling rust, but that is based on the old makefile approach and doesn't seem to be working.
When following the commands from [this github issue](https://github.com/rust-lang/rust/issues/42043) I get a compiled libstd, but not rustc. Is there any documentation on how to cross-compile rustc that you're aware of? I don't seem to be able to guess based on the build system options and random posts I find on the interwebs...

**Comment by japaric** [comment]
I haven't cross compiled rustc in a long time but it went like this, iirc:

``` console
$ # export CC, AR and CXX
$ export CC_arm_unknown_linux_gnueabihf=arm-unknown-linux-gnueabihf-gcc

$ # I want to cross compile a toolchain (rustc) for this host
$ ./configure --host=arm-unknown-linux-gnueabihf

$ # bootstrap the compiler and cross compile rustc
$ # there are ways to do this faster by not bootstraping the compiler but I don't remember them anymore
$ ./x.py
```

x.py is documented [here](https://github.com/rust-lang/rust/blob/master/src/bootstrap/README.md).

**Comment by apopiak** [comment]
Thank you for pointing that out. I thought I could set WHERE I am building
by hand (by setting the host parameter) ^^
BTW. Thank you so much for all the cross compilation stuff you've already
figured out and the tools you've built, it's been a great help!

2017-11-16 0:54 GMT+01:00 Jorge Aparicio <notifications@github.com>:
