### ISSUE TITLE
Windows x86_64 docker image is missing v0.1.13 tag

### ISSUE THREAD

**Issue by jan-auer** [japaric/cross#151]
Builds for target `x86_64-pc-windows-gnu` fail with:

```
Error response from daemon: manifest for japaric/x86_64-pc-windows-gnu:v0.1.13 not found.
```

The tag is missing on Dockerhub

**Comment by japaric** [comment]
The travis build (that builds and uploads the Docker images) failed for that target because of some network error. I have restarted it; let's [see](https://travis-ci.org/japaric/cross/jobs/298848367) if it succeeds this time. If it does a new image will be uploaded.

**Comment by japaric** [comment]
The tag is up now.
