### ISSUE TITLE
Unsupported syscall: SYS_memfd_create

### ISSUE THREAD

**Issue by gnzlbg** [japaric/cross#191]
I am using cross in travis-ci and I am seeing the following regression on the following targets:

qemu-aarch64 => qemu: Unsupported syscall: 279
qemu-arm => qemu: Unsupported syscall: 385
qemu-mips => qemu: Unsupported syscall: 4354
qemu-mips64 => qemu: Unsupported syscall: 5314
qemu-powerpc => qemu: Unsupported syscall: 360
qemu-powerpc64 => qemu: Unsupported syscall: 360

amongst others. The offending syscall is `SYS_memfd_create`.

**Comment by gnzlbg** [comment]
@japaric I think that this is the commit that broke this: https://github.com/japaric/cross/commit/6918a42b8e617c3f87bb5b153c03e987331ab496

**Comment by gnzlbg** [comment]
@malbarbo any thoughts on this, I was relying on `cross` for CI, but now it broke backwards compatibility. Should I just use an older cross version until this is fixed? If so, which version should I use?

**Comment by Dylan-DPC** [comment]
Hey

Feels odd that a revert is breaking. Are you sure that commit is reponsible?

**Comment by gnzlbg** [comment]
It seems that Ubuntu 12.xx does not have a kernel with `memfd_create` while Ubuntu 14.xx does which is exactly what that commit was changing and would explain the error I am getting. 

My library started using `memfd_create` after `cross` was updated to it (it did not use it before), and once the revert landed, my build bots started failing.

**Comment by Dylan-DPC** [comment]
Fair. But that PR was reverting a commit which means that your app would break even before the upgrade to 14.04 took place. Is that the case?

**Comment by gnzlbg** [comment]
> Is that the case?

Yes, I just triple-checked and this is the commit where I introduced `memfd_create`:

* https://travis-ci.org/gnzlbg/slice_deque/jobs/350424417#L553
* cross version: cross v0.1.14

For some reason the tests still pass... so maybe that's a bug in `cross`?

Looks like this is a bug in qemu: https://bugs.launchpad.net/qemu/+bug/1734792 so I am closing this. Thanks and sorry for the noise!

**Comment by Dylan-DPC** [comment]
It is okay :)
