### ISSUE TITLE
can't call `git` from a `build.rs` file

### ISSUE THREAD

**Issue by gnzlbg** [japaric/cross#204]
I have a `build.rs` file that calls git but `cross build` errors with:

```shell
fatal: unable to look up current user in the passwd file: no such user
Unexpected end of command stream
```

**Comment by gnzlbg** [comment]
Maybe just passing `--volume /etc/passwd:/etc/passwd:ro \` to `docker` would fix this?

**Comment by jamesmunns** [comment]
That seems... probably too aggressive (this gives the container access to your hashed passwords and list of users). 

If git is only running this to determine the current user, you might try calling the git config commands (in your container) before running the rest of your script, e.g. something like:

```
git config user.name "Cross Runner"
git config user.email cross@github.com
```

**Comment by gnzlbg** [comment]
I actually think that using `git` from a `build.rs` file was a bad idea in the first place.
