### ISSUE TITLE
Add a C++ cross-compiler/cross-compiled libstdc++

### ISSUE THREAD

**Issue by dflemstr** [japaric/cross#31]
(This is a feature request)

Since OpenSSL is available in the Docker images, I think it would make sense for there to be a C++ environment as well; arguably it's more common to depend on a C++ library that needs to be cross-compiled than depending on OpenSSL (maybe OpenSSL is more common when dealing with network-related libraries?).

There would need to be a compiler available for the target platform; there would preferably also be an `ENV` layer in the Docker image that sets environment variables that are compatible with https://github.com/alexcrichton/gcc-rs (e.g. `HOST_CXX`, `TARGET_CXX`)

Of course `libstdc++` would also be cross-compiled and match the chosen compiler.

**Comment by japaric** [comment]
> t's more common to depend on a C++ library that needs to be cross-compiled than depending on OpenSSL

Is it? Thanks god I haven't had to deal with C++ libraries so far. Having to compile C code is already bad.

Anyhow, do you have an example of a crate, preferably a binary one, that has to build C++ code? So we can actually test this.

**Comment by dflemstr** [comment]
Many C++ crates bind to system libraries that would need to be cross-compiled too (like my nemesis [`v8`](https://crates.io/crates/v8)) so let's not pick one of those.  What I would like to do eventually though is to use `cross` to build [`rq`](https://github.com/dflemstr/rq) instead of my own [hacked together](https://github.com/dflemstr/rq/blob/master/ci#L28-L57) cross compilation (that file might be interesting for some cross-compilation pitfalls btw), but that's also a huge project to cross-compile.

One that I maintain that is very small and self-contained is [`vcdiff`](https://crates.io/crates/vcdiff); that one might be a good candidate for testing C++ support.

By the way, I already set up my own set of Docker images for cross compilation, but they all use `crosstool-ng` and all use the latest GCC/etc so they aren't very good for backwards compatibility.  However they work great for cross-compiling `v8` and `rq` etc.

**Comment by dflemstr** [comment]
My cross-compilation images (just run `make` to build them; maybe uncomment the `docker push`): https://github.com/dflemstr/buildenv

**Comment by japaric** [comment]
Thanks. vcdiff looks like a good crate to test all this.

I was hoping to not have to use crosstool-ng at all but it seems that I'll have to use it for the arm-unknown-linux-gnueabi* targets anyway. In any case, we should try to use minimize the number of toolchains that have to be build with crosstool-ng (because build times, etc.).
