### ISSUE TITLE
cross hangs when building the `curl-sys` crate

### ISSUE THREAD

**Issue by japaric** [japaric/cross#4]
for these targets

- `mips-unknown-linux-gnu`
- `mips64-unknown-linux-gnuabi64`
- `powerpc64-unknown-linux-gnu`

I have no idea why. This doesn't even involve QEMU.

cc @alexcrichton. Any tip on how to debug a build scripts that hangs/blocks? There's no output file so I can't inspect the stdout/stderr of the build script.

**Comment by japaric** [comment]
By manually placing some `panic!` calls in the build script, at least I know that the build script hangs when it shells out to [`sh configure ...`](https://github.com/alexcrichton/curl-rust/blob/curl-sys-0.3.6/curl-sys/build.rs#L168).

**Comment by alexcrichton** [comment]
I've found gdb helpful for attaching to live processes or you can also just kill the build script itself and then take a look at the logs to see how far it go

**Comment by japaric** [comment]
OK, so apparently this a bug in `curl-sys` build script. cc @alexcrichton

In a nutshell, the configure line I linked before should be:

```
$ configure --build=$HOST --host=$TARGET --target=TARGET (..)
```

[Source](http://www.matteomattei.com/how-to-cross-compile-curl-library-with-ssl-and-zlib-support/)

---

Explanation:

Right now, `curl-sys`' build script calls `configure` like this:

```
$ configure --host=$HOST --target=TARGET (..)
```

which causes the `configure` script to sometimes "probe the environment" like this:

```
# where conftest.c changes for each "test"
$ $TARGET-gcc conftest.c
$ ./conftest
```

which is **wrong** because this is running a binary e.g. for MIPS on e.g. a
x86_64 system and as a result, on most systems, this "test" will always fail.
On those systems, this is not *too* bad because most tests don't involve calling
`conftest` .

However, this is particularly bad for *this* project because I'm cross building
`curl-sys` on a system that *has* transparent QEMU emulation enabled so
`./conftest` is actually being executed and sometimes hangs (possibly due to
QEMU).

---

If I actually change the build script to call `configure` like this:

```
$ configure --build=$HOST --host=$TARGET --target=TARGET (..)
```

Then `configure` never calls `./conftest` to probe environment (but it still
calls `$TARGET-gcc conftest.c`). With that change `curl-sys` cross compiles fine
for `mips-unknown-linux-gnu`
