### ISSUE TITLE
Change gcc/ld/ar version.

### ISSUE THREAD

**Issue by Emilgardis** [japaric/cross#41]
Trying to get this to work correctly and one thing I want to do is use the `thumbv7em-none-eabi` target. I want to use 6.2.0/ but cross provides 4.9.3. How do I change this (if possible)

**Comment by japaric** [comment]
`cross` uses Docker containers. You can override the default Docker image by creating a *local* image named `japaric/thumbv7em-none-eabi:v0.1.3` (or `:latest` if `cross -V` returns a `-dev` version).

> but cross provides 4.9.3

The Docker images for the thumb* targets are based on Ubuntu 16.04 and that's the gcc version it provides. Ubuntu 16.10 also ships with 4.9.3. If you know of a distribution that ships with gcc and that has an image on Docker Hub, it'd be happy to change the image `cross` is using right now.

**Comment by japaric** [comment]
> it'd be happy to change the image cross is using right now.

We could also build a custom toolchain on Ubuntu 16.04 and use that ... but I'd prefer not to do that as it (a) we may configure gcc wrongly and (b) it would signicantly increase the CI times of this repo.

**Comment by Emilgardis** [comment]
I see. I'm not so familiar with docker, so I'm going to get myself more familiar with it. I'll come back and edit this with information on how I fixed it (if I manage to).

**Comment by Emilgardis** [comment]
Closed by #44
