### ISSUE TITLE
Add support for custom docker images

### ISSUE THREAD

**Issue by Emilgardis** [japaric/cross#42]
Cross is lacking support for custom docker images. Custom images should be used either by default or optionally.

## Option 1:
Cross looks on launch for an image called `<target>:<tag>` where `<tag>` is optionally specified with a flag `--tag` (if none then default tag, i.e `latest` or latest tagged version). If successful, cross will later launch docker with the specified image. If unsucessful, cross will load `japaric/<target>:<tag>` (`<tag>` is also the default here). Cross will also take a `docker-image` flag to fully specify what image to be used, i.e using `other-user/foo:<tag>` or `<local-image>:<tag>` where the user simply gives the full path to cross.

## Option 2:
Cross does the same as Option 1 but doesn't look for another image but `japaric/<target>:<tag>`unless any is specified.

### Things to consider
- `cargo --tag` is currently undefined, however it could be used in the feature, using `--docker-tag` could be safer to use for future compatability reasons.
- Instead of just using flags for `cross --docker-image myimage`, also consider using enviromental variables for this, possible even using [dotenv]. 
- When user specifies a full path to an image, parse it with `docker_image.replace("{target}", target)` so that when using `cross --target=<target> --docker-image={target}:v0.1.0`, the docker-image will be expanded and set to `<target>:v0.1.0`.

[dotenv]: https://crates.io/crates/dotenv

**Comment by Alexhuszagh** [comment]
A major enhancement to this was implemented in #678.
