### ISSUE TITLE
Is there a way to tell if cross is being used via. build script?

### ISSUE THREAD

**Issue by SirDoctors** [japaric/cross#75]
We have migrations that we run with the build script, and we want to check if Travis is installed as that would apply whether or not migrations should be run by the build script.

**Comment by japaric** [comment]
I don't really understand the use case. Do you want to Cross to behave differently when it's called by a build script?

The Travis stuff you mention seems like it could be handled by a build script like this:

``` rust
// build.rs

fn main() {
    if env::var_os("TRAVIS_OS_NAME").is_some() {
        Command::new("cross").arg("run").(..)
    }
}
```

**Comment by SirDoctors** [comment]
Wow I feel silly for not considering that, thanks.
